### ISSUE TITLE
Upgrade the Go version of the demo app

### ISSUE THREAD

**Issue by mchurichi** [HewlettPackard/galadriel#72]
The app in `/demo/greeter` uses an outdated version of Go, and it is being [reported by Trivy](https://github.com/HewlettPackard/galadriel/pull/71/checks?check_run_id=9995043837) as having several High and Medium-risk dependencies vulnerabilities . We need to upgrade the Go version (maybe matching the same version Galadriel uses) along with these dependencies.

**Comment by Victorblsilveira** [comment]
I think that this was solved here:  https://github.com/HewlettPackard/galadriel/pull/92

**Comment by mchurichi** [comment]
You're right! thanks Victor ❤️
